#!/bin/bash

if [ ! -f session_id ]; then
  echo "No session_id file found."
  exit 1
fi

sessid=$(cat session_id)
day=$1
last_year=`if [ $(date +%m) -eq 12 ]; then date +%Y; else expr $(date +%Y) - 1; fi`
year=${2:-$last_year}

mkdir -p $year

inputfile=$year/input$(printf "%02d" $day).py
echo "v = \"\"\"" > $inputfile
curl -b session=$sessid https://adventofcode.com/$year/day/$day/input >> $inputfile
echo "\"\"\"" >> $inputfile
